# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Sparkle_config = debug
  Application_config = debug

else ifeq ($(config),releasee)
  GLFW_config = releasee
  Sparkle_config = releasee
  Application_config = releasee

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Sparkle Application

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Sparkle/vendor/Glfw -f Makefile config=$(GLFW_config)
endif

Sparkle: GLFW
ifneq (,$(Sparkle_config))
	@echo "==== Building Sparkle ($(Sparkle_config)) ===="
	@${MAKE} --no-print-directory -C Sparkle -f Makefile config=$(Sparkle_config)
endif

Application: Sparkle GLFW
ifneq (,$(Application_config))
	@echo "==== Building Application ($(Application_config)) ===="
	@${MAKE} --no-print-directory -C Application -f Makefile config=$(Application_config)
endif

clean:
	@${MAKE} --no-print-directory -C Sparkle/vendor/Glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Sparkle -f Makefile clean
	@${MAKE} --no-print-directory -C Application -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  releasee"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Sparkle"
	@echo "   Application"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"